{% set name = "asciidoctor" %}
{% set version = "2.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: bbd1e1d16deed8db94bf9624b9f4474fac32d9ca7225d377f076c08d9adde387

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r asciidoctor -e 'exit 0'
    - asciidoctor -V

about:
  home: https://asciidoctor.org
  license: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: A fast, open source text processor and publishing toolchain for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - awvwgk
